[theme]
primaryColor = "#0075be"
# Se quiser adicionar mais cores de tema, coloque-as aqui dentro, sem repetir [theme]

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[server]
headless = true